name: mobile_rsi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  http: ^0.13.4
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.4.0
  smooth_page_indicator: ^1.2.0+3
  webview_flutter: ^4.9.0
  onesignal_flutter: ^5.2.5
  permission_handler: ^11.3.1
  bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0



flutter:
  uses-material-design: true
  assets:
    - assets/promo1.jpeg
    - assets/promo2.jpeg
    - assets/promo3.jpeg
    - assets/promo4.jpeg
    - assets/promo5.jpeg
    - assets/promo6.jpeg
    - assets/promo7.jpeg
    - assets/promo8.jpeg
    - assets/promo9.jpeg
    - assets/promo10.jpeg
    - assets/promo11.jpeg
    - assets/promo12.jpeg
    - assets/promo13.jpeg
    - assets/Rsi.png
    - assets/IMMA.png
    - assets/LatarLogo.png
    - assets/biruLatar.png
    - assets/putih.png
    - assets/LatarMenu.png
    - assets/Logo_Rsi.png
    - assets/selamatdatang.png
    - assets/SignIn.png
    - assets/SignUp.png
    - assets/LatarMenu.png
    - assets/LatarSemua.png
    - assets/login.png
    - assets/Pendaftaran.png
    - assets/CekKamar.png
    - assets/HasilPemeriksaan.png
    - assets/JadwalDokter.png
    - assets/KritikSaran.png
    - assets/RiwayatObat.png
    - assets/ResepSaya.png
    - assets/WA.png
    - assets/TiketSaya.png
    - assets/TombolDaftar.png
    - assets/PasienBpjs.png
    - assets/PasienMitra.png
    - assets/PasienTunai.png
    - assets/ImmaApps.png
    - assets/immaText.png
    - assets/gedung.png
    - assets/2024.png
    - assets/inputlogin.png
    - assets/Peserta.png
    - assets/waLogo.png
    - assets/bed.png
    - assets/immaText.png
    - assets/mobile.png


    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
